### ISSUE TITLE
Need to get correct copy for initial page.

### ISSUE THREAD

**Issue by elliotblanchard** [tambien/Ring#12]
Need to talk to eMuze about correct copy for opening page.

**Comment by elliotblanchard** [comment]
I got the official copy for this page from eMuze - here it is:

"Introducing Ring. Introducing emuze.

emuze is a destination for discovering and sharing the content you love from today's best artists and entertainers.

Ring shows you how the latest news about SXSW's hottest artists moves through social media. From the first tweet to the final reblog, watch how big news spreads throughout the world.

Ring is on Twitter too! Follow @emuzeRing for cool facts about artists at SXSW and tweet @emuzeRing with new hashtags or artists you think we should include!"

**Comment by elliotblanchard** [comment]
Two other quick things:
1. Can we center the type in the loading bar - "BEGIN", etc.
2. Can we change the loading message from the band names to "Loading artist 2/10" etc

**Comment by tambien** [comment]
it's "emuze" and not "eMuze"?

**Comment by elliotblanchard** [comment]
eMuze is correct - good catch
