### ISSUE TITLE
Need to fix time range display.

### ISSUE THREAD

**Issue by elliotblanchard** [tambien/Ring#14]
Need to fix the way time range is displayed around the ring so that it's not just a 24 hour clock.

**Comment by tambien** [comment]
done! with some animations. the reblog lines get kinda weird sometimes when you enlarge the date range.

**Comment by elliotblanchard** [comment]
Agh. Sorry to keep reopening things. We need to do something with the reblog lines getting munged during the date range change. I know you've been knocking away at this and it's been a bitch. If we need to, we should just do it that everything "un-builds", the "re-builds" in the new date positions, rather than trying to shift the existing shapes, if that fixes it.

**Comment by elliotblanchard** [comment]
Oh - one more thing about this interim animation - if we can just turn down the springiness a little, that would be awesome.

**Comment by tambien** [comment]
fixed this bug finally!

do you want the springy-ness all the way off?
