### ISSUE TITLE
Need soloing/highlighting of selected shape/branch.

### ISSUE THREAD

**Issue by elliotblanchard** [tambien/Ring#18]
Need some sort of emphasis of the selected shape - as in the boards - getting larger and with yellow ring. And some sort of emphasis of the selected branch of reblogs in the case of tumblr.

**Comment by tambien** [comment]
i put the ring in, but it's barely visible because the line is so thin. please resent it with a thicker line. only if you really squint can you see it.

**Comment by elliotblanchard** [comment]
![yellow_ring_thicker](https://f.cloud.github.com/assets/3344010/233076/8f9ff860-8748-11e2-96e5-86531b236806.png)
Here you go!
