### ISSUE TITLE
Need to include the non-Chrome browser catch panel.

### ISSUE THREAD

**Issue by elliotblanchard** [tambien/Ring#21]
We need to put up the panel that catches non-Chrome browsers - do you have that board from me?

**Comment by elliotblanchard** [comment]
![Ring_06a_Chrome_Redirect](https://f.cloud.github.com/assets/3344010/212204/b100e660-82d7-11e2-8f03-49ceb47ebea0.png)

**Comment by tambien** [comment]
i do a feature detection instead of a browser test. that means that it does not REQUIRE chrome, but chrome is the only browser that supports these features right now. if Safari and Firefox both implement these features soon, it'll run on those browsers without this screen.

**Comment by elliotblanchard** [comment]
Hmm - it's actually rejecting my Chrome browser now - OSX 25.0.1364.152

**Comment by tambien** [comment]
that should be fixed now.
