### ISSUE TITLE
Need the info data area added and styled.

### ISSUE THREAD

**Issue by elliotblanchard** [tambien/Ring#24]
We need to add (and style) the info area that's below the "Hide Options" button - the area that shows the date range, what is shown, number of posts, etc.

**Comment by tambien** [comment]
is the "posts found" count how many posts are being displayed at that moment, or the number of posts found (from the top 26), or the total posts in the database? 

right now i have it as the number of posts downloaded for the top 26 for the past week.

**Comment by elliotblanchard** [comment]
I think it makes most sense to have that "posts found" number be the number of posts being displayed at the moment - band X date range X reblog level

**Comment by elliotblanchard** [comment]
Can we make the type that is now purple that "Ring Yellow"? Low priority.
