### ISSUE TITLE
Need to add and style the search panel.

### ISSUE THREAD

**Issue by elliotblanchard** [tambien/Ring#26]
We need to get the search panel in there as part of the larger styling effort.

**Comment by tambien** [comment]
done. made only the last four searches visible in the artists list.

**Comment by elliotblanchard** [comment]
Nice! One thing I've noticed - you can't add a band from the search if it has an "&" in the name - like "Macklemore & Ryan Lewis" - clicking the Search button won't add it. (LOW PRIORITY)

Also, realized that this will be useless on the touchscreen version since they have no keyboard?

**Comment by tambien** [comment]
I've fixed this & problem. 

i've started to make an "installation" version. it's almost exactly the same, but i'm going to switch a flag that says, "installation = true", and i'm going to put it at ring.invisiblelightnetwork.com/installation.html. 

I'm going to remove the search feature from the installation version for now.
