### ISSUE TITLE
Need to add the "Visit eMuze" button.

### ISSUE THREAD

**Issue by elliotblanchard** [tambien/Ring#29]
Need to add and style the "Visit eMuze" button below the "Show Options" button.

**Comment by elliotblanchard** [comment]
Gah. Just realized that this should only be in the internet version - otherwise they'll open up a new chrome window in the projector, and not have any way to ever close it without a keyboard. If we don't have time to add the code to sense if the client is internet or projector, we should just drop it.

**Comment by tambien** [comment]
i've excluded this button from the installation version, but it will still be available in the web version. 

we should consider adding a longer tag list to the installation version since loading time is not an issue, we can go back to top 26.

**Comment by elliotblanchard** [comment]
Yep, totally - the longer tag list for the installation version is perfect.
