### ISSUE TITLE
Some shapes should be behind knockout shape.

### ISSUE THREAD

**Issue by elliotblanchard** [tambien/Ring#3]
Right now, I see the knockout shape, but nothing seems to be partially behind it. Of course, it should really only be the bigger polys/circles that would go behind, so they'd still be partially visible.

**Comment by tambien** [comment]
one way that i get higher performance out of the particle system is by turning off depth sorting. the systems are sorted (in the z axis) relative to other particles in the system, but not to other objects in the scene. 

i will explore this issue a little more.

**Comment by elliotblanchard** [comment]
That's fine then - don't worry about it - although, I do notice that the knockout shape cuts off some shapes inside it (see bottom edge of the screenshot) - this is a low priority.
![Screen Shot 2013-03-04 at 10 37 17 AM](https://f.cloud.github.com/assets/3344010/217147/6f2a1e1c-84e1-11e2-907c-acf863afd43b.png)
