### ISSUE TITLE
Any possible way to anti-alias the lines?

### ISSUE THREAD

**Issue by elliotblanchard** [tambien/Ring#31]
Just wondering if there was any way to antialias the l-system lines. Low priority.

**Comment by tambien** [comment]
i've tried a little, and i think the answer is no. i'll come back to this one.

**Comment by elliotblanchard** [comment]
Maybe we try dropping the transparency of the lines down to 75% or 50%? Sometimes that helps. LOW PRIORITY

**Comment by tambien** [comment]
i put it at 50%, but it still has aliasing.
