### ISSUE TITLE
Need "attract mode" for the FEED space version.

### ISSUE THREAD

**Issue by elliotblanchard** [tambien/Ring#32]
Just remembered this one - we need some sort of attract mode for the FEED space version the automatically runs through parameters, etc.

**Comment by elliotblanchard** [comment]
I've just started thinking about this - perhaps it's something like.
- Once loading is complete, Ring auto-picks 3 artists to plot, for a random date range, with reblogs on, so there's something to start with.
- If there's no input for like a minute - Ring will close the Options panel, and cycle through clicking on various posts for say another minute, maybe having each up for a few seconds.
- Then Ring picks another three, etc, etc.

**Comment by tambien** [comment]
what i have right now is after a minute of no touches, it starts a random walk through the options. at a random interval between 5-8 seconds, it will randomly select an artist, date range, reblog level, or show one of the info popovers on a post. 

do you think the options panel should be closed for this? i think it might be interesting to see how the ranges change.

**Comment by elliotblanchard** [comment]
Cool - yeah, totally agree that it's cooler if it pops the option panel open when it's in autopilot mode to see the ranges changing.
