### ISSUE TITLE
Touchscreen taps on smaller posts problematic.

### ISSUE THREAD

**Issue by elliotblanchard** [tambien/Ring#45]
Often there's no response to a tap on an area of small posts - I'm not sure if it's b/c the area has a lot of small posts, or just the size. A couple of people have noticed it - it's just a simple frustration thing. Can we increase the area around a "touch" that the program searches to find a post to display the info window for so that they get a response? Or is it a problem of the app not knowing which post to display in crowded areas, and then showing nothing?

**Comment by tambien** [comment]
it's still not perfect, but it's better now.
