### ISSUE TITLE
Animation - build

### ISSUE THREAD

**Issue by elliotblanchard** [tambien/Ring#6]
Be nice to have some sort of build animation, now that we've got the good performance. Something that built clockwise around the shape, and then out from the center to the reblogs would be awesome. Also good if there was some sort of reverse build followed by a new build out that happened as time/parameters were changed. Any sort of the spring feel that you'd mentioned would also be great.

**Comment by elliotblanchard** [comment]
Notice there's a bug in the un-build animation. In cases where there are a lot of posts on the screen, sometimes the un-build animation freezes for awhile, or breaks completely, with branches just flickering on and off.

**Comment by elliotblanchard** [comment]
Just another thought - because I know you mentioned that it might be very difficult to get the "growing" animation for the tree shapes - growing out from the center - happening smoothly, here's an alternative. Instead of a smooth animation, perhaps we can just turn on each branch and node in sequence from the inner part of the ring out to the end of the reblog chain for each post - that would get the feel of each tree growing logically, but maybe less of a bitch to animate.

**Comment by tambien** [comment]
i don't have the posts growing outward, but the trees grow outward and meet up with the posts. it kind of gives the illusion of the whole thing growing outward. 

i added springyness because you mentioned you wanted that kind of force-directed graph force simulation, but i can take that off.

**Comment by elliotblanchard** [comment]
Cool - I think, if post-Friday, we can just have the post shapes scale up in place as the branch section that supports them appear, as opposed to zooming in from the corners - that could be cool.
