### ISSUE TITLE
Faster loading/better documented loading.

### ISSUE THREAD

**Issue by elliotblanchard** [tambien/Ring#8]
We have to figure out how to make the loading process seem faster, and actually be faster. Right now, it's running at about 30 seconds on my pretty decent Mac Pro desktop. 

I think part of this is definitely some sort of loading bar with a loading status attached that breaks down the process into smaller pieces. We can work together on this.

But we also have to figure out some sort of way to get the actual time down a bit as well. I know it's tough because there's so much data. Maybe it loads the top ten first and then streams the rest in. I just know no-one is going to hold out that long right now.

**Comment by elliotblanchard** [comment]
![Ring_06a_Loading](https://f.cloud.github.com/assets/3344010/212205/c3075e52-82d7-11e2-8a90-32ef0ff66704.png)

**Comment by elliotblanchard** [comment]
Thought the simplest way to do the loading bar was just have it occupy the same space and turn into the "Begin" button when it's finished.

**Comment by tambien** [comment]
so i dropped it from top 26 to top 12 artists. though, this doesn't make as big of a difference as you might imagine since the bulk of the posts are concentrated in the first few artists and there seems to be an exponential drop off.

**Comment by elliotblanchard** [comment]
Yeah, that's true. Well, hopefully dropping the orphan reblogs, tumblr posts that we don't parse will help - plus adding the "verbose" loading progress bar on the the welcome panel.

**Comment by tambien** [comment]
dropping the orphaned blogs and tumblr posts that don't parse didn't help as much as i had hoped. the loading feels like it takes less time now that you can see the artists names as they're being loaded.
